/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as HowToBuyRouteImport } from './routes/how-to-buy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioWebRouteImport } from './routes/portfolio.web'
import { Route as PortfolioSocialRouteImport } from './routes/portfolio.social'
import { Route as PortfolioManagementRouteImport } from './routes/portfolio.management'
import { Route as PortfolioDesignRouteImport } from './routes/portfolio.design'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToBuyRoute = HowToBuyRouteImport.update({
  id: '/how-to-buy',
  path: '/how-to-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioWebRoute = PortfolioWebRouteImport.update({
  id: '/portfolio/web',
  path: '/portfolio/web',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSocialRoute = PortfolioSocialRouteImport.update({
  id: '/portfolio/social',
  path: '/portfolio/social',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioManagementRoute = PortfolioManagementRouteImport.update({
  id: '/portfolio/management',
  path: '/portfolio/management',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDesignRoute = PortfolioDesignRouteImport.update({
  id: '/portfolio/design',
  path: '/portfolio/design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/packages': typeof PackagesRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/design': typeof PortfolioDesignRoute
  '/portfolio/management': typeof PortfolioManagementRoute
  '/portfolio/social': typeof PortfolioSocialRoute
  '/portfolio/web': typeof PortfolioWebRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/packages': typeof PackagesRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/design': typeof PortfolioDesignRoute
  '/portfolio/management': typeof PortfolioManagementRoute
  '/portfolio/social': typeof PortfolioSocialRoute
  '/portfolio/web': typeof PortfolioWebRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to-buy': typeof HowToBuyRoute
  '/packages': typeof PackagesRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/portfolio/design': typeof PortfolioDesignRoute
  '/portfolio/management': typeof PortfolioManagementRoute
  '/portfolio/social': typeof PortfolioSocialRoute
  '/portfolio/web': typeof PortfolioWebRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-to-buy'
    | '/packages'
    | '/shop'
    | '/testimonials'
    | '/portfolio/design'
    | '/portfolio/management'
    | '/portfolio/social'
    | '/portfolio/web'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-to-buy'
    | '/packages'
    | '/shop'
    | '/testimonials'
    | '/portfolio/design'
    | '/portfolio/management'
    | '/portfolio/social'
    | '/portfolio/web'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/how-to-buy'
    | '/packages'
    | '/shop'
    | '/testimonials'
    | '/portfolio/design'
    | '/portfolio/management'
    | '/portfolio/social'
    | '/portfolio/web'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToBuyRoute: typeof HowToBuyRoute
  PackagesRoute: typeof PackagesRoute
  ShopRoute: typeof ShopRoute
  TestimonialsRoute: typeof TestimonialsRoute
  PortfolioDesignRoute: typeof PortfolioDesignRoute
  PortfolioManagementRoute: typeof PortfolioManagementRoute
  PortfolioSocialRoute: typeof PortfolioSocialRoute
  PortfolioWebRoute: typeof PortfolioWebRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-buy': {
      id: '/how-to-buy'
      path: '/how-to-buy'
      fullPath: '/how-to-buy'
      preLoaderRoute: typeof HowToBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/web': {
      id: '/portfolio/web'
      path: '/portfolio/web'
      fullPath: '/portfolio/web'
      preLoaderRoute: typeof PortfolioWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/social': {
      id: '/portfolio/social'
      path: '/portfolio/social'
      fullPath: '/portfolio/social'
      preLoaderRoute: typeof PortfolioSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/management': {
      id: '/portfolio/management'
      path: '/portfolio/management'
      fullPath: '/portfolio/management'
      preLoaderRoute: typeof PortfolioManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/design': {
      id: '/portfolio/design'
      path: '/portfolio/design'
      fullPath: '/portfolio/design'
      preLoaderRoute: typeof PortfolioDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToBuyRoute: HowToBuyRoute,
  PackagesRoute: PackagesRoute,
  ShopRoute: ShopRoute,
  TestimonialsRoute: TestimonialsRoute,
  PortfolioDesignRoute: PortfolioDesignRoute,
  PortfolioManagementRoute: PortfolioManagementRoute,
  PortfolioSocialRoute: PortfolioSocialRoute,
  PortfolioWebRoute: PortfolioWebRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
